# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=56)),
                ('excel_file', models.FileField(upload_to=b'files/uploads')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
    ]
