# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_examuploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exam_subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Stream'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, choices=[(b'HM', b'Head Teacher'), (b'DP', b'Deputy teacher'), (b'SM', b'Senior Master'), (b'CT', b'Class Teacher'), (b'EH', b'Examination Head'), (b'AA', b'Academic Affairs'), (b'HOS', b'Head of Sciences'), (b'HOH', b'Head of Humanities'), (b'HOL', b'Head of Languages'), (b'HOM', b'Head of Mathematics')], max_length=4, null=True),
        ),
    ]
