# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0003_auto_20160404_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Stream'),
        ),
    ]
