# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0004_auto_20160404_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easy.Subject'),
        ),
    ]
